stomp:
  inbox: "/topic/activepush"
  hosts:
    - host: "localhost"
      port: 61613
      ssl: false
      login: "guest"
      passcode: "guest"

logging:
  level: "WARN"
  file: "log/activepush.log"

http:
  port: 9191
